
#cd mongodb-main
#
#for schema in catalogue.js users.js ; do
#mongo < ${schema} &>>LOG_FILE
#done
#
# For loop applied above for below comand
#  echo lodaing catalogue schema
# mongo < catalogue.js &>>$LOG_FILE
#statuscheck $?

#echo  load user schema
#mongo < users.js &>>$LOG_FILE
#statuscheck $?

- name: Setup MONgodb Repo
  ansible.builtin.copy:
    src: mongo.repo    #---->> this is file we copied content of repo & pasted in file directory
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install Mongodb package
  ansible.builtin.yum:
    name: mongodb-org
    state: installed

- name: updating ipaddress for mongodb
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start Mongod Service
  ansible.builtin.systemd:
    name: mongod
    state: restarted
    enabled: yes

- name: downloading Database Schema & Extract
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/mongodb/archive/main.zip
    dest: /tmp
    remote_src: yes

# cd /tmp
# unzip mongodb.zip --->>> already done above
# cd mongodb-main   ---->> below module
# mongo < catalogue.js
# mongo < users.js

- name: Load Catalogue Schema
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb.main/catalogue.js"
    idempotent: yes
# above play  path we pulled from above cd /tmp/mongodb-main & file is catalogue.js
- name: Load users Schema
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb.main/users.js"
    idempotent: yes
# here path we pulled from above cd /tmp/mongodb-main & file is users.js