- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Enable service Nginx
  ansible.builtin.service:
    name: nginx
    enabled: yes

- name: Start service Nginx
  ansible.builtin.service:
    name: nginx
    state: started

