- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

#Start nginx service placed down as per requirement in code

#- name: Download Nginx web content  (substitute below line 21 both download & extract in one play)
#  ansible.builtin.get_url:
#    url: https://github.com/roboshop-devops-project/frontend/archive/main.zip
#    dest: /tmp/frontend.zip

- name: Removing old web content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

# COmmented these lines to move towards standard process of downloading the content from artifact manager(NEXUS) rather than download from GIT
#
#- name: Download Nginx web content & Extract
#  ansible.builtin.unarchive:
 #   src: https://github.com/roboshop-devops-project/frontend/archive/main.zip
  #  dest: /tmp
   # remote_src: yes

#- name: COpy extracted content
#  ansible.builtin.copy:
#    src: /tmp/frontend-main/static/  #using / after static to copy whole content
#    dest: /usr/share/nginx/html/
#    remote_src: yes

- name: Create application directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: Downloading Application content
  ansible.builtin.unarchive:
    src: http://{{NEXUS_USER}}:{{NEXUS_PASS}}@nexus.roboshop.internal:8081/repository/{{COMPONENT}}/{{COMPONENT}}-{{APP_VERSION}}.zip
    dest: /usr/share/nginx/html
    remote_src: yes



# mv frontend-main/localhost.conf /etc/nginx/default.d/roboshop.conf (Replacing of local host with robo.conf pending)
- name: Copy Roboshop Nginx COnfig File
  ansible.builtin.copy:
    src: roboshop.conf # This file we created in roles>frontend>files>roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf
  notify: Restart Nginx Service

# mv frontend-main/localhost.conf /etc/nginx/default.d/roboshop.conf (will do later for replacing local host)

- name: Start Nginx Service
  ansible.builtin.systemd:  #(A single module will take care for start service & enable)
    state: started # starting service (earlier it was restarted we are using handler if above config changes then use handler to restart here check handler file)
    name: nginx
    enabled: yes # enabling service




