#curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash &>>$LOG_FILE
#statuscheck $?
#
#echo "Install Erland & Rabbitmq"
#yum install https://github.com/rabbitmq/erlang-rpm/releases/download/v25.1/erlang-25.1-1.el8.x86_64.rpm rabbitmq-server -y &>>$LOG_FILE
#statuscheck $?
#
#echo "start rabbitmq server"
#systemctl enable rabbitmq-server &>>LOG_FILE
#systemctl start rabbitmq-server &>>LOG_FILE
#statuscheck $?
#
#rabbitmqctl list_users | grep roboshop &>>LOG_FILE
#if [ $? -ne 0 ]; then
#echo "Add app user in rabbitmq"
#rabbitmqctl add_user roboshop roboshop123 &>>LOG_FILE
#statuscheck $?
#fi
#
#echo "add app user tag in rabbitmq"
#rabbitmqctl set_user_tags roboshop administrator &>>LOG_FILE
#statuscheck $?
#
#echo "add permission for app user in rabbitmq"
#rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*" &>>LOG_FILE
#statuscheck $?

- name: Setup Rabbitmq Repos
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

- name: Install Erland & RabbitMq
  ansible.builtin.yum:
    name: "{{item}}"
    state: installed
    disable_gpg_check: yes
  loop:
    - https://github.com/rabbitmq/erlang-rpm/releases/download/v25.1.1/erlang-25.1.1-1.el8.x86_64.rpm
    - rabbitmq-server

- name: Start RabbitMQ server
  ansible.builtin.systemd:
    name: rabbitmq-server
    enabled: yes
    state: started

- name: Add Applocation User
  community.rabbitmq.rabbitmq_user:
    user: roboshop                                #echo "add app user tag in rabbitmq"
    password: "{{ROBOSHOP_RABBITMQ_PASSWORD}}"    # Will user this ROBOSHOP_RABBITMQ_PASSWORD=roboshop@123 (password ) while executing play from cmd
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
    tags: administrator             #echo "add permission for app user in rabbitmq"